version: "3.9"

services:
  images-service:
    image: ricardoyalico/glossy-images:latest   # üëà versi√≥n fija
    container_name: glossy-images
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/glossy-db

    depends_on:
      - db

    networks:
      - glossy-net

  backend-service:
    image: ricardoyalico/glossy-backend:latest
    container_name: glossy-backend
    restart: unless-stopped

    ports:
      - "8080:8080"

    depends_on:
      - db

    networks:
      - glossy-net
      
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/glossy-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: postgres:15
    container_name: glossy-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: glossy-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

    # ‚ùó solo si necesitas acceso externo
    ports:
      - "5432:5432"

    networks:
      - glossy-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: glossy-cloudflared
    restart: unless-stopped

    command: tunnel run
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}

    depends_on:
      - images-service

    networks:
      - glossy-net

volumes:
  postgres_data:

networks:
  glossy-net:
    driver: bridge
