version: "3.9"

services:
  frontend-service:
    image: ricardoyalico/glossy-frontend:latest
    container_name: glossy-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - glossy-net

  images-service:
    image: ricardoyalico/glossy-images:latest   # üëà versi√≥n fija
    container_name: glossy-images
    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - db

    networks:
      - glossy-net

  backend-service:
    image: ricardoyalico/glossy-backend:latest
    container_name: glossy-backend
    restart: unless-stopped

    ports:
      - "8080:8080"

    env_file:
      - .env

    depends_on:
      - db

    networks:
      - glossy-net

      
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/glossy-db
    #   SPRING_DATASOURCE_USERNAME: postgres
    #   SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: postgres:15
    container_name: glossy-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    # ‚ùó solo si necesitas acceso externo
    ports:
      - "5432:5432"

    networks:
      - glossy-net

cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: glossy-cloudflared
    restart: unless-stopped

    # Forzar HTTP/2 para evitar problemas con QUIC
    command: tunnel --protocol http2 run
    
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}

    # Configurar DNS para resolver correctamente las regiones de Cloudflare
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4

    cap_add:
      - NET_ADMIN
    
    sysctls:
      - net.core.rmem_max=7500000
      - net.core.wmem_max=7500000
      
    depends_on:
      - images-service

    networks:
      - glossy-net

    # Opcional: limitar logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:

networks:
  glossy-net:
    driver: bridge
